### ISSUE TITLE
Crashed when multiple studies

### ISSUE THREAD

**Issue by emmanuels7** [dicomsort/dicomsort#107]
Hi. Thanks for your work on this useful software.

I realize that DicomSort easily crashes on windows 10 when there are multiple studies. Furthermore, immediately crashes when there are studies with the same name. 

Is there any newer version in mind?

I have this report:

locals()

```
Type: <type 'dict'>

Value: {'pp': <bound method Display.setItem of <wx.py.crust.Display; proxy of <Swig Object of type 'wxStyledTextCtrl *' at 0x108ea240> >>, 'shell': <wx.py.shell.Shell; proxy of <Swig Object of type 'wxStyledTextCtrl *' at 0x49d3b48> >, 'lib': 'C:\\Program Files (x86)\\DICOM Sort/lib', '__builtins__': <module '__builtin__' (built-in)>, 'gui': <module 'gui' from 'C:\Program Files (x86)\DICOM Sort/lib\gui\__init__.pyc'>, '__package__': None, 'sys': <module 'sys' (built-in)>, 'filling': <wx.py.filling.Filling; proxy of <Swig Object of type 'wxSplitterWindow *' at 0x27473b8> >, 'notebook': <wx._controls.Notebook; proxy of <Swig Object of type 'wxNotebook *' at 0x27479a0> >, '__name__': '__main__', 'app': <gui.DicomSort; proxy of <Swig Object of type 'wxPyApp *' at 0x48674f8> >, '__doc__': None}
```

Regards

**Comment by suever** [comment]
Thanks for the bug report @emmanuels7. I'll take a look this week and will follow-up in this ticket.

**Comment by suever** [comment]
@emmanuels7 Do you mind checking to see if this issue still persists with the [3.0.0 version of DICOM Sort](https://github.com/dicomsort/dicomsort/releases/tag/v3.0.0) that I just released?

**Comment by suever** [comment]
Going to go ahead and close this but feel free to re-open if you are still experiencing issues @emmanuels7
