### ISSUE TITLE
Dicom sort 2.1.9 not working on Mac OS 10.15 Catalina

### ISSUE THREAD

**Issue by PascalTetreault** [dicomsort/dicomsort#116]
After installing DICOM sort 2.1.9 in the application folder, trying to run does not work and I have a popup message simply saying impossible to open the DICOM Sort-2.1.9 application.

Thanks a lot!

**Comment by suever** [comment]
@PascalTetreault This should be addressed in the [3.0.0 version of DICOM Sort](https://github.com/dicomsort/dicomsort/releases/tag/v3.0.0) that I just released. I'll go ahead and close this issue but feel free to open another up if you continue to have issues.
