### ISSUE TITLE
Epic Fail if trying to access an opened locked document

### ISSUE THREAD

**Issue by lrq3000** [dicomsort/dicomsort#36]
If DicomSort tries to read a document that is locked (eg, an excel file), it will result in an Epic Fail:

> --------------DO NOT EDIT BELOW ------------
> Traceback (most recent call last):
> 
>   File "C:\Users\IEUser\dicomsort\gui\__init__.py", line 458, in FillList
> 
>   File "C:\Users\IEUser\dicomsort\dicomsorter.py", line 442, in GetAvailableFields
> 
>   File "C:\Users\IEUser\dicomsort\dicomsorter.py", line 52, in isdicom
> 
>   File "C:\Python27\lib\site-packages\dicom\filereader.py", line 589, in read_file
> 
> IOError: [Errno 13] Permission denied: u'C:\path_redacted\\~$copy of some excel file.xlsm'
>

**Comment by suever** [comment]
Thanks for reporting @lrq3000 I'll work on getting a fix out for this to prevent future issues!

**Comment by lrq3000** [comment]
Actually I think it's good to have an exception raised in these cases (because we might miss dicoms if it's dicoms that are locked), but it would be good to have an option to skip the error ;-)

**Comment by suever** [comment]
Going to go ahead and close this unless we still think it is a priority in which I am happy to discuss. I'd like to tackle this as a larger ability to "quarantine" bad files so that the user can revisit any issues but they don't prevent others from being processed.
